name: Generate TypeScript Definitions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # Updated to JDK 21
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: npm install
          
      - name: Clone LiquidBounce NextGen
        run: |
          git clone https://github.com/CCBlueX/LiquidBounce.git lbng
          cd lbng
          git checkout 451cb31e9bf093fe07f9b28202bc2471921ea13d  # Version 0.29.0 release
      
      - name: Download Latest ts-generator
        run: |
          mkdir -p lbng/run/LiquidBounce/scripts
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/commandblock2/ts-generator/releases/latest | jq -r '.assets[] | select(.name | endswith(".zip")) | .browser_download_url')
          curl -L $LATEST_RELEASE_URL -o lbng/run/LiquidBounce/scripts/ts-generator.zip
          unzip lbng/run/LiquidBounce/scripts/ts-generator.zip -d lbng/run/LiquidBounce/scripts/
          # Look specifically for the main jar file (excluding source jars)
          find lbng/run/LiquidBounce/scripts/ -name "*.jar" -not -name "*-sources.jar" -not -name "*-src.jar" -exec mv {} lbng/run/LiquidBounce/scripts/ts-generator.jar \; || echo "Main JAR file not found in the zip, check contents"

      - name: Copy ts-defgen.js to LiquidBounce scripts
        run: |
          cp LBNG-script/ts-defgen.js lbng/run/LiquidBounce/scripts/
          
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Run LiquidBounce with Gradle
        working-directory: ./lbng
        env:
          CI_BUILD: "true"  # Set the CI_BUILD flag to auto-execute ts-defgen
        run: |
          chmod +x ./gradlew
          timeout 60m xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" ./gradlew runClient -Dfabric.headless=true || exit 0
          
      - name: Copy Generated Definitions
        run: |
          mkdir -p generated-modules
          cp -r lbng/run/LiquidBounce/scripts/types-gen generated-modules/

      - name: Apply Patches
        run: npm run apply-patches
        
      - name: Install Generated Definitions
        run: npm install file:./generated-modules/types-gen/jvm/ --no-save
        
      # - name: Compile TypeScript
      #   run: |
      #     mkdir -p dist
      #     npm run compile
        
      - name: Upload TypeScript Definitions
        uses: actions/upload-artifact@v4
        with:
          name: typescript-definitions
          path: generated-modules/types-gen
          
      - name: Upload Compiled Scripts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-scripts
          path: dist
